---
title: Master's Degree Course of Data Mining
summary: Notes on my master's degree course of data mining
author: André Felipe Berdusco Menezes
date: '2022-02-25'
draft: false
categories:
  - master's degree
  - data mining
  - logistic regression
  - decision tree
  - support vector machines
  - random forest
  - boosting
  - bagging
output:
  blogdown::html_page:
    toc: true
    number_sections: false
    toc_depth: 1
---

## About

Data mining is a very common concept nowadays. Nonetheless, there is still a
misunderstanding what exactly is data mining. Perhaps, this is due to the fact that data
mining is a wide concept that covers several fields of knowledge, from mathematics and
statistics to computer science.

My Master's Degree course of data mining was very naive with focus on classification
methods, although the syllabus was more broad.
The main references I have used to study were:

- [The Elements of Statistical Learning: Data Mining, Inference, and Prediction](https://hastie.su.domains/ElemStatLearn/)

- [An Introduction to Statistical Learning](https://www.statlearning.com/)

- [Machine Learning A Probabilistic Perspective](https://www.amazon.com.br/Machine-Learning-Probabilistic-Perspective/dp/0262018020)

## Course assignments

The lessons were taught by professor [Ronaldo Dias](https://www.ime.unicamp.br/~dias/).
The assessment method adopted were practical data analysis of real world data sets with
focus on comparison between the classification methods. More precisely, I have done the
following reports and presentation:


- [Binary Classifications: A study to classify patients with heart disease](https://github.com/AndrMenezes/dm2019/raw/master/work1/report1.pdf)

- [Decision Trees: Bagging, Random Forest and Boosting](https://github.com/AndrMenezes/dm2019/raw/master/work2/presentation2.pdf)

- [An Empirical Comparison between Support Vector Machines and Logistic Regression](https://github.com/AndrMenezes/dm2019/raw/master/work3/report3.pdf)

All analysis were conducted in R software and the codes are available in my
[Github repository](https://github.com/AndrMenezes/dm2019).

